"""Markdown renderers: per-agent job spec (`agents/<id>/plan.md`) and `PLAN.md`. See docs/CONTRACTS.md §4."""

from __future__ import annotations

from pathlib import Path

from whiteboard.plan.model import AgentCard, Node, interface_text

PLAN_MD_NOTICE = (
    "> Generated by the whiteboard server from `.whiteboard/plan/` — do not hand-edit. "
    "Edit node files under `plan/nodes/` or the diagrams instead."
)


def node_rel_path(node: Node) -> str:
    return f".whiteboard/plan/nodes/{node.id}.md"


def _md_cell(text: object) -> str:
    return str(text if text is not None else "").replace("|", "\\|").replace("\n", " ")


def _bullets(items: list[str], empty: str = "- (none)") -> str:
    return "\n".join(f"- {i}" for i in items) if items else empty


def _interface_lines(node: Node) -> list[str]:
    return [f"`{interface_text(i)}`" for i in node.interfaces]


def render_job_spec(
    node: Node,
    deps: list[Node],
    dependents: list[Node],
    project_root: Path,
    collaboration_rel: str = ".whiteboard/COLLABORATION.md",
) -> str:
    """The job spec handed to the subagent working on `node`."""
    root = Path(project_root)
    node_path = root / (node.path or node_rel_path(node))
    collab_path = root / collaboration_rel
    plan_path = root / ".whiteboard" / "PLAN.md"

    body = node.body.strip()
    goal_lines = [f"**{node.title}** (`{node.id}`, type `{node.type}`)"]
    if body:
        goal_lines += ["", body]

    dep_lines: list[str] = []
    for d in deps:
        dep_lines.append(f"- `{d.id}` — {d.title} (status: {d.status})")
        for i in d.interfaces:
            dep_lines.append(f"  - `{interface_text(i)}`")
        if not d.interfaces:
            dep_lines.append("  - (no declared interfaces)")

    dependent_lines = [f"- `{d.id}` — {d.title} (status: {d.status})" for d in dependents]

    sections = [
        f"# Job spec: {node.title}",
        "",
        "## Goal",
        "",
        *goal_lines,
        "",
        "## Your node file path",
        "",
        f"`{node_path}`",
        "",
        "Update its body with design notes and progress; the server keeps the frontmatter in sync.",
        "",
        "## Status protocol",
        "",
        "Use the `whiteboard` MCP server, tool names exactly as written:",
        "",
        f'1. First thing: `mcp__whiteboard__set_agent_status(agent_id=<your agent id>, status="working")`.',
        f'2. Questions for the human: `mcp__whiteboard__ask_user(agent_id=<your agent id>, question=..., node_id="{node.id}")`, '
        "then poll `mcp__whiteboard__get_reply(prompt_id=...)`.",
        f'3. Last thing: `mcp__whiteboard__append_event(agent_id=<your agent id>, node_id="{node.id}", type="done", note=<what landed + test counts>)` '
        '— or `type="blocked"` / `type="needs_input"` with a note explaining why.',
        "",
        "`done` marks the node done and notifies the agents that depend on it; do not call it before your tests pass.",
        "",
        "## Interfaces you must provide",
        "",
        _bullets(_interface_lines(node), "- (none declared — propose them in your node file body)"),
        "",
        "## Interfaces you consume",
        "",
        "\n".join(dep_lines) if dep_lines else "- (no dependencies)",
        "",
        "## Dependents waiting on you",
        "",
        _bullets(dependent_lines, "- (none)") if dependent_lines else "- (none)",
        "",
        "## Diagrams you must produce",
        "",
        f"- Before you report `done`, refresh the LLD for `{node.id}`: "
        "`mcp__whiteboard__write_agent_diagram(agent_id=<your agent id>, mermaid=...)`.",
        "- One box per module, class or table you actually built; box ids there are free-form "
        "(they are your components, not plan node ids).",
        "- If the design deviates from this spec, rewrite it with "
        "`mcp__whiteboard__write_agent_plan(agent_id=<your agent id>, plan_md=...)` so the canvas shows the truth.",
        "- Report at every milestone: "
        "`mcp__whiteboard__report_progress(agent_id=<your agent id>, activity=..., progress=0.0-1.0)`.",
        "",
        "## Scope rules",
        "",
        "- Only touch paths relevant to this node.",
        "- Never edit other nodes' files under `.whiteboard/plan/nodes/`; report needed changes via `append_event` instead.",
        f"- Read `{collab_path}` before doing anything else and follow it.",
        "- Do not message other agents about each other's work; everything goes through events.",
        "",
        "## Read first",
        "",
        f"- `{collab_path}`",
        f"- `{plan_path}`",
        f"- `{node_path}`",
        "",
    ]
    return "\n".join(sections)


def render_plan_md(
    nodes: dict[str, Node],
    agents: dict[str, AgentCard],
    diagram_mermaid: str,
    boards: dict[str, str] | None = None,
) -> str:
    """`PLAN.md`: overview tables, the full flowchart, one section per board
    (`boards` maps a board name to its mermaid) and one section per node."""
    lines: list[str] = ["# PLAN", "", PLAN_MD_NOTICE, "", "## Nodes", ""]
    lines += ["| id | title | type | status | owner | depends_on |", "|---|---|---|---|---|---|"]
    for n in nodes.values():
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{n.id}`",
                    _md_cell(n.title),
                    n.type,
                    n.status,
                    f"`{n.owner}`" if n.owner else "—",
                    ", ".join(f"`{d}`" for d in n.depends_on) or "—",
                ]
            )
            + " |"
        )
    if not nodes:
        lines.append("| — | (no nodes yet) | | | | |")

    lines += ["", "## Agents", ""]
    lines += ["| id | assigned_node | status | ready_deps |", "|---|---|---|---|"]
    for a in agents.values():
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{a.id}`",
                    f"`{a.assigned_node}`" if a.assigned_node else "—",
                    a.status,
                    ", ".join(f"`{d}`" for d in a.ready_deps) or "—",
                ]
            )
            + " |"
        )
    if not agents:
        lines.append("| — | (no agents yet) | | |")

    mermaid = (diagram_mermaid or "").strip("\n")
    lines += ["", "## Flowchart", "", "```mermaid", mermaid if mermaid else "flowchart TD", "```", ""]

    lines += ["## Boards", ""]
    for name, board_mermaid in (boards or {}).items():
        text = (board_mermaid or "").strip("\n")
        lines += [
            f"### {name.upper()} (`plan/{name}.md`)",
            "",
            "```mermaid",
            text if text else "flowchart TD",
            "```",
            "",
        ]
    if not boards:
        lines += ["(no boards)", ""]

    lines += ["## Node details", ""]
    for n in nodes.values():
        lines += [
            f"### {n.title} (`{n.id}`)",
            "",
            f"- file: [`plan/nodes/{n.id}.md`](plan/nodes/{n.id}.md)",
            f"- type: `{n.type}` · status: `{n.status}` · owner: {f'`{n.owner}`' if n.owner else '—'}",
            f"- depends_on: {', '.join(f'`{d}`' for d in n.depends_on) or '—'}",
        ]
        if n.interfaces:
            lines.append("- interfaces:")
            lines += [f"  - `{interface_text(i)}`" for i in n.interfaces]
        lines.append("")
    if not nodes:
        lines += ["(no nodes yet)", ""]
    return "\n".join(lines)


__all__ = ["PLAN_MD_NOTICE", "node_rel_path", "render_job_spec", "render_plan_md"]
