"""Markdown renderers: per-agent job spec (`agents/<id>/plan.md`) and `PLAN.md`. See docs/CONTRACTS.md §4."""

from __future__ import annotations

from pathlib import Path

from whiteboard.plan.model import AgentCard, Node, interface_text

PLAN_MD_NOTICE = (
    "> Generated by the whiteboard server from `.whiteboard/plan/` — do not hand-edit. "
    "Edit node files under `plan/nodes/` or the diagrams instead."
)


def node_rel_path(node: Node) -> str:
    return f".whiteboard/plan/nodes/{node.id}.md"


def _md_cell(text: object) -> str:
    return str(text if text is not None else "").replace("|", "\\|").replace("\n", " ")


def _bullets(items: list[str], empty: str = "- (none)") -> str:
    return "\n".join(f"- {i}" for i in items) if items else empty


def _interface_lines(node: Node) -> list[str]:
    return [f"`{interface_text(i)}`" for i in node.interfaces]


def render_job_spec(
    node: Node,
    deps: list[Node],
    dependents: list[Node],
    project_root: Path,
    collaboration_rel: str = ".whiteboard/COLLABORATION.md",
    agent_id: str | None = None,
) -> str:
    """The job spec handed to the subagent working on `node`.

    `agent_id` is substituted into every tool call so the spec is self-sufficient even for a
    `general-purpose` agent; without it the calls keep the `<your agent id>` placeholder.
    """
    root = Path(project_root)
    node_path = root / (node.path or node_rel_path(node))
    collab_path = root / collaboration_rel
    plan_path = root / ".whiteboard" / "PLAN.md"
    aid_arg = f'"{agent_id}"' if agent_id else "<your agent id>"
    agent_dir = root / ".whiteboard" / "agents" / (agent_id or "<your agent id>")

    body = node.body.strip()
    goal_lines = [f"**{node.title}** (`{node.id}`, type `{node.type}`)"]
    if body:
        goal_lines += ["", body]

    dep_lines: list[str] = []
    for d in deps:
        dep_lines.append(f"- `{d.id}` — {d.title} (status: {d.status})")
        for i in d.interfaces:
            dep_lines.append(f"  - `{interface_text(i)}`")
        if not d.interfaces:
            dep_lines.append("  - (no declared interfaces)")

    dependent_lines = [f"- `{d.id}` — {d.title} (status: {d.status})" for d in dependents]

    sections = [
        f"# Job spec: {node.title}",
        "",
        "## Goal",
        "",
        *goal_lines,
        "",
        "## Your node file path",
        "",
        f"`{node_path}`",
        "",
        "Update its body with design notes and progress; the server keeps the frontmatter in sync.",
        "",
        "## Status protocol",
        "",
        "Use the `whiteboard` MCP server, tool names exactly as written:",
        "",
        "If the `mcp__whiteboard__*` tools are not available in your session, stop immediately and say which "
        "tool is missing in your final message: without them nothing you do is recorded and the root session "
        "cannot see you.",
        "",
        f'1. First thing: `mcp__whiteboard__set_agent_status(agent_id={aid_arg}, status="working")`.',
        f'2. Questions for the human: `mcp__whiteboard__ask_user(agent_id={aid_arg}, question=..., node_id="{node.id}")`, '
        "then poll `mcp__whiteboard__get_reply(prompt_id=...)`.",
        f'3. Last thing: `mcp__whiteboard__append_event(agent_id={aid_arg}, node_id="{node.id}", type="done", note=<what landed + test counts>)` '
        '— or `type="blocked"` / `type="needs_input"` with a note explaining why.',
        "",
        "`done` marks the node done and notifies the agents that depend on it; do not call it before your tests pass.",
        "",
        "## Interfaces you must provide",
        "",
        _bullets(_interface_lines(node), "- (none declared — propose them in your node file body)"),
        "",
        "## Interfaces you consume",
        "",
        "\n".join(dep_lines) if dep_lines else "- (no dependencies)",
        "",
        "## Dependents waiting on you",
        "",
        _bullets(dependent_lines, "- (none)") if dependent_lines else "- (none)",
        "",
        "## Progress reporting",
        "",
        f"`mcp__whiteboard__report_progress(agent_id={aid_arg}, activity=<one short present-tense line>, "
        'progress=<0.0-1.0>, metrics={"tool_calls": <n>, "elapsed_s": <n>}, '
        "files_touched=[<paths changed since your last report>])`",
        "",
        "Call it at every milestone:",
        "",
        "1. after reading this spec, the node and every dependency (`progress ≈ 0.1`);",
        "2. after each file or coherent group of files lands;",
        "3. before the test run and again after it;",
        "4. immediately before `done` (`progress = 1.0`).",
        "",
        "`files_touched` is deduped and accumulated server-side. `tokens_in`, `tokens_out` and `cost_usd` "
        "are filled in by the root session — do not send them.",
        "",
        "The human watches this live. Never report progress you have not made.",
        "",
        "## Chat",
        "",
        "Owner chat reaches you as a message telling you to answer. Answer in your own thread: "
        f"`mcp__whiteboard__chat_reply(from_id={aid_arg}, text=<your answer>)`.",
        "",
        "Your final message is not a reply — it is not read until you exit. Never post in another agent's "
        "thread and never answer on the owner's behalf in the `root` thread.",
        "",
        "## If your plan changes",
        "",
        "If you must deviate from this spec, rewrite it first: "
        f"`mcp__whiteboard__write_agent_plan(agent_id={aid_arg}, plan_md=<updated spec>)`. The spec on disk "
        "must always describe what you are actually doing.",
        "",
        "If the owner edits your plan mid-run you are told the event number N. Stop what you are doing, "
        f"re-read `{agent_dir / 'plan.md'}` in full, then acknowledge with "
        f"`mcp__whiteboard__report_progress(agent_id={aid_arg}, activity=<what changes>, ack_event_seq=N)` "
        "**before** doing anything else.",
        "",
        "## Scope rules",
        "",
        "- Only touch paths relevant to this node.",
        "- Never edit other nodes' files under `.whiteboard/plan/nodes/`; report needed changes via `append_event` instead.",
        f"- Read `{collab_path}` before doing anything else and follow it.",
        "- Do not message other agents about each other's work; everything goes through events.",
        "",
        "## Read first",
        "",
        f"- `{collab_path}`",
        f"- `{plan_path}`",
        f"- `{node_path}`",
        "",
    ]
    return "\n".join(sections)


def render_plan_md(nodes: dict[str, Node], agents: dict[str, AgentCard], diagram_mermaid: str) -> str:
    """`PLAN.md`: overview tables, the full flowchart and one section per node."""
    lines: list[str] = ["# PLAN", "", PLAN_MD_NOTICE, "", "## Nodes", ""]
    lines += ["| id | title | type | status | owner | depends_on |", "|---|---|---|---|---|---|"]
    for n in nodes.values():
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{n.id}`",
                    _md_cell(n.title),
                    n.type,
                    n.status,
                    f"`{n.owner}`" if n.owner else "—",
                    ", ".join(f"`{d}`" for d in n.depends_on) or "—",
                ]
            )
            + " |"
        )
    if not nodes:
        lines.append("| — | (no nodes yet) | | | | |")

    lines += ["", "## Agents", ""]
    lines += ["| id | assigned_node | status | ready_deps |", "|---|---|---|---|"]
    for a in agents.values():
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{a.id}`",
                    f"`{a.assigned_node}`" if a.assigned_node else "—",
                    a.status,
                    ", ".join(f"`{d}`" for d in a.ready_deps) or "—",
                ]
            )
            + " |"
        )
    if not agents:
        lines.append("| — | (no agents yet) | | |")

    mermaid = (diagram_mermaid or "").strip("\n")
    lines += ["", "## Flowchart", "", "```mermaid", mermaid if mermaid else "flowchart TD", "```", ""]

    lines += ["## Node details", ""]
    for n in nodes.values():
        lines += [
            f"### {n.title} (`{n.id}`)",
            "",
            f"- file: [`plan/nodes/{n.id}.md`](plan/nodes/{n.id}.md)",
            f"- type: `{n.type}` · status: `{n.status}` · owner: {f'`{n.owner}`' if n.owner else '—'}",
            f"- depends_on: {', '.join(f'`{d}`' for d in n.depends_on) or '—'}",
        ]
        if n.interfaces:
            lines.append("- interfaces:")
            lines += [f"  - `{interface_text(i)}`" for i in n.interfaces]
        lines.append("")
    if not nodes:
        lines += ["(no nodes yet)", ""]
    return "\n".join(lines)


__all__ = ["PLAN_MD_NOTICE", "node_rel_path", "render_job_spec", "render_plan_md"]
